### ISSUE TITLE
FRI Connection Quality Drops and Disconnects

### ISSUE THREAD

**Issue by OmidRezayof** [lbr-stack/lbr_fri_ros2_stack#194]
Hi @mhubii! It's me again :)
Hope you're doing okay. 
I have recently discovered the FRI connection quality drops during execution of LBRServer and it leads to disconnection of FRI. This happens even when the only code running is the lbr_bringup to connect robot the robot and sunrise to FRI.
I have attached the error when this happens. 
I would greatly appreciate any kind of solutions to this matter.
![image](https://github.com/lbr-stack/lbr_fri_ros2_stack/assets/143108739/4558fb4d-fde9-4c85-8072-2b450a30ecf4)

**Comment by mhubii** [comment]
no worries. It is a little difficult to debug this issue remotely. Can you pinpoint this to a connection error? Does this error persist when you restart the robot?

What OS / ROS version are you running etc? Are you running inside a Docker container? Are you using the latest `humble` branch of this repository? **Can you see some output on the terminal of your PC? Maybe there are joint limits?**

I recently found that the joint limit check sometimes disconnects when it is close to a limit. There might be some numerical issues there. I presume the robot goes slightly or measures joint positions beyond the limits (noise or what not).

This line might be related:

https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/bf61e8f01171309150041f54a74deddd86af68d9/lbr_fri_ros2/src/command_guard.cpp#L33

**Comment by OmidRezayof** [comment]
So I'm using ROS Humble on Ubuntu 22.04 LTS Jammy. And no I'm not using a docker. 
Yes the codes are almost up to date with the latests commits on Humble branch.
Regarding the joint limits, the issue is, even when the robot is in a safe position and not in motion and no other codes are running, the FRI disconnects occasionally. So I don't think it is a joint limit issue?

**Comment by mhubii** [comment]
okay makes sense. What control rate are you running the robot at? Maybe try decrease that rate if your computer can't keep up or check your ethernet cable. Maybe launch with `rviz:=false`.

Other than that I really don't know what the issue here could be. The robot communication thread runs asynchronously, doesn't do much work, and is non-blocking, so communication should be guaranteed. 

There is the possibility of assigning a higher thread priority on a real-time OS. On a realtime kernel, the priority is set here:

https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/bf61e8f01171309150041f54a74deddd86af68d9/lbr_fri_ros2/src/app.cpp#L92

It is taken from the configuration file:

https://github.com/lbr-stack/lbr_fri_ros2_stack/blob/bf61e8f01171309150041f54a74deddd86af68d9/lbr_ros2_control/config/lbr_system_parameters.yaml#L9

Maybe we should make this configurable on any OS.

**Comment by OmidRezayof** [comment]
So, after trying a ton of different things, it looks like one of the LAN cables was dead inside and it was causing the connection to drop. Replacing that lan cable solved the problems (or at least looks like!). I will close this issue now. Thanks @mhubii again for your support everytime!
