### ISSUE TITLE
FRI Session Could Not Be Established

### ISSUE THREAD

**Issue by MrstupidJ** [lbr-stack/lbr_fri_ros2_stack#24]
Hi we have followed all the steps to conenct the robot controller to the windows PC to setup the LBR Server application in the controller. Now we are trying to establish a connection between the robot and the linux computer running ROS2 application. However, when we start the LBR server from the Kuka Smart Pad we are getting the following error which points to that the error is coming due to configuration issues. We have gone over the network configuration multiple times and they all seem correct. Are we meant to run a certain version of the sunrise software? We are currently running Sunrise Workbench - Med 1.15.

We do not have access to your school's sharepoint to look at any of the additional resources. We are able to successfully ping the robot controller from the linux computer. 

![Screenshot from 2022-11-15 11-26-32](https://user-images.githubusercontent.com/41416997/201796233-53e336a1-304b-4218-9f8b-6a1c6935035c.png)

Please look at this image of the error we get from the smart pad. It is pointing at this [line](https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/blob/0d2cc6e2f6bcfbff860fa87ecb87a64520f55181/server/fri_ros2/LBRServer.java#L111) 

![error_page1](https://user-images.githubusercontent.com/41416997/201794423-00ef1fe5-c6a6-48f3-a9e2-4cbf50b96fcc.png)
![error_page2](https://user-images.githubusercontent.com/41416997/201796008-30c5825a-aa7e-4bfe-9c73-d6a849b6cb2e.png)

Any help here would be greatly appreciated.

**Comment by mhubii** [comment]
hey @MrstupidJ , are you sure you configured the network correctly? From the image above, it seems there are issues with pinging the robot, ie DUP!. The robot has 2 ethernet ports, KONI under `192.170.10.2` and the non real-time one under X66, `172.31.1.147`. Where did you plug in the ethernet cable? I would also recommend you to run the robot in T1 mode rather than AUT mode for now

**Comment by mhubii** [comment]
on another note, in the launch file [here](https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/blob/0d2cc6e2f6bcfbff860fa87ecb87a64520f55181/lbr_bringup/launch/lbr_control.launch.py#L69), chrt is a linux command to launch an executable with real-time priority. This might not work on windows and cause the hardware interface not to be launched. In order to work on linux, you have to edit the real-time priority of your user. So you might want to comment that out for now. We are working on making this optional in the launch file, but are also busy doing research, so pull-requests are always welcomed. Thank you for the feedback

**Comment by mhubii** [comment]
also you set the the Client command mode to `NO_COMMAND_MODE`. This defines what the commands you send to the robot. To begin with, select `POSITION`

**Comment by MrstupidJ** [comment]
Thanks for your reply @mhubii ! 

I commented out the [line](https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/blob/0d2cc6e2f6bcfbff860fa87ecb87a64520f55181/lbr_bringup/launch/lbr_control.launch.py#L69)  you mentioned and it worked! 

Just to clarify, the DUP! thing is normal when you try to Ping the KUKA FRI. It seems like it means to do so to achieve high frequency real-time data exchange. And yes it is a good and safe practice to run in T1 mode first,

**Comment by mhubii** [comment]
great, thank you for the feedback!
